"""
Ranking Report Generator

Responsibilities:
- Populate HTML template with ranking data
- Generate radar chart images
- Generate score comparison bar charts
- Save final HTML report
"""

import logging
import json
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime
import base64
from io import BytesIO

logger = logging.getLogger(__name__)


class RankingReportGenerator:
    """Generates HTML reports for strategy ranking results"""

    def __init__(self, template_path: Path = None):
        """
        Initialize report generator

        Args:
            template_path: Path to HTML template (defaults to shared/templates/)
        """
        if template_path is None:
            template_path = (
                Path(__file__).parent.parent
                / "templates"
                / "ranking_report_template.html"
            )

        self.template_path = Path(template_path)
        self.template_content = None

        if self.template_path.exists():
            with open(self.template_path, "r", encoding="utf-8") as f:
                self.template_content = f.read()
        else:
            logger.warning(f"Template not found: {self.template_path}")

    def generate_report(
        self,
        ranking_results: Dict[str, Any],
        output_dir: Path = None
    ) -> str:
        """
        Generate HTML report from ranking results

        Args:
            ranking_results: Results from strategy ranking engine
            output_dir: Output directory (defaults to frontend/control/)

        Returns:
            Path to generated HTML report
        """
        if output_dir is None:
            output_dir = Path(__file__).parent.parent.parent / "frontend" / "control"

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate report filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_file = output_dir / f"ranking_report_{timestamp}.html"

        logger.info(f"Generating report: {report_file}")

        # Build report content
        html_content = self._build_report_html(ranking_results)

        # Write report
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(html_content)

        logger.info(f"Report generated: {report_file}")
        return str(report_file)

    def _build_report_html(self, ranking_results: Dict[str, Any]) -> str:
        """
        Build final HTML report content

        Args:
            ranking_results: Ranking results dict

        Returns:
            HTML content string
        """
        if not self.template_content:
            return self._build_minimal_report(ranking_results)

        html = self.template_content

        # Extract data
        ranked_strategies = ranking_results.get("ranked_strategies", [])
        metadata = ranking_results.get("ranking_metadata", {})

        # Replace metadata placeholders
        html = html.replace(
            '<span id="analysisTime">N/A</span>',
            f'<span id="analysisTime">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</span>'
        )
        html = html.replace(
            '<span id="outputCombination">summary</span>',
            f'<span id="outputCombination">{metadata.get("output_combination", "summary")}</span>'
        )
        html = html.replace(
            '<span id="baselinePlan">N/A</span>',
            f'<span id="baselinePlan">{metadata.get("baseline_plan_name", "N/A")}</span>'
        )
        html = html.replace(
            '<span id="strategyCount">0</span>',
            f'<span id="strategyCount">{len(ranked_strategies)}</span>'
        )

        # Build ranking table rows
        table_rows_html = self._build_ranking_table_rows(ranked_strategies)
        html = html.replace(
            '<!-- Generated by JavaScript -->',
            table_rows_html,
            1  # Replace only first occurrence (in table)
        )

        # Build top strategy scores
        if ranked_strategies:
            top_strategy = ranked_strategies[0]
            top_scores_html = self._build_score_cards(top_strategy["scores"])
            html = html.replace(
                '<div class="score-breakdown" id="topStrategyScores">',
                f'<div class="score-breakdown" id="topStrategyScores">\n{top_scores_html}\n'
            )

        # Build executive summary
        summary_html = self._build_executive_summary(ranked_strategies, metadata)
        html = html.replace(
            '<div class="summary-text" id="executiveSummary">\n                评估报告正在生成...\n            </div>',
            summary_html
        )

        # Add chart data as inline script
        chart_script = self._build_chart_script(ranked_strategies)
        html = html.replace(
            '<script>\n        // This script will be populated by Python report generator\n        // Placeholder for dynamic content\n    </script>',
            f'<script>\n{chart_script}\n    </script>'
        )

        return html

    def _build_ranking_table_rows(self, ranked_strategies: List[Dict]) -> str:
        """Build HTML rows for ranking table"""
        rows = []

        for strategy in ranked_strategies:
            rank = strategy["rank"]
            rank_class = f"rank-{rank}" if rank <= 3 else ""
            recommendation = strategy["recommendation"]
            rec_class = self._get_recommendation_class(recommendation)
            scores = strategy["scores"]

            # Format scores with color coding
            overall_score = strategy["overall_score"]
            score_class = self._get_score_class(overall_score)

            row = f"""
                <tr>
                    <td class="rank-cell {rank_class}">🥇</td>
                    <td>{strategy['plan_name']}</td>
                    <td class="score {score_class}"><strong>{overall_score:.1f}</strong></td>
                    <td><span class="recommendation-badge recommendation-{rec_class}">{recommendation}</span></td>
                    <td class="score">{scores['effectiveness']:.1f}</td>
                    <td class="score">{scores['coverage']:.1f}</td>
                    <td class="score">{scores['efficiency']:.1f}</td>
                    <td class="score">{scores['reliability']:.1f}</td>
                </tr>
            """
            rows.append(row)

        return "\n".join(rows)

    def _build_score_cards(self, scores: Dict[str, float]) -> str:
        """Build HTML for score cards"""
        cards = []

        dimensions = [
            ("有效性", "effectiveness", scores.get("effectiveness", 0)),
            ("覆盖率", "coverage", scores.get("coverage", 0)),
            ("效率", "efficiency", scores.get("efficiency", 0)),
            ("可靠性", "reliability", scores.get("reliability", 0)),
        ]

        for label, key, value in dimensions:
            card = f"""
                <div class="score-card {key}">
                    <div class="score-card-title">{label}</div>
                    <div class="score-card-value">{value:.1f}</div>
                </div>
            """
            cards.append(card)

        return "\n".join(cards)

    def _build_executive_summary(
        self,
        ranked_strategies: List[Dict],
        metadata: Dict[str, Any]
    ) -> str:
        """Build executive summary HTML"""
        if not ranked_strategies:
            return '<div class="summary-text warning">未找到任何策略评估结果</div>'

        top_strategy = ranked_strategies[0]
        baseline_name = metadata.get("baseline_plan_name", "基准方案")

        summary = f"""
            <div class="summary-text">
                <strong>🎯 最优策略: {top_strategy['plan_name']}</strong><br>
                总体评分 <span style="color: #2196F3; font-weight: bold;">{top_strategy['overall_score']:.1f}/100</span>，
                推荐等级为"<strong>{top_strategy['recommendation']}</strong>"。
                相比{baseline_name}，该方案在有效性、覆盖率和效率上均有显著提升。
            </div>
            <div class="summary-text info">
                📊 本次评估共纳入 <strong>{len(ranked_strategies)}</strong> 个控制策略。
                系统采用多准则评估方法，综合考虑策略的有效性、覆盖率、效率和可靠性，
                为交通管理者提供科学的决策支持。
            </div>
        """

        return summary

    def _build_chart_script(self, ranked_strategies: List[Dict]) -> str:
        """Build JavaScript for rendering charts"""
        if len(ranked_strategies) < 2:
            return "// Insufficient data for charts"

        # Prepare data for radar chart (top 3 strategies)
        top_strategies = ranked_strategies[:3]
        labels = ["有效性", "覆盖率", "效率", "可靠性"]

        # Build radar chart script
        radar_datasets = []
        colors = [
            {"border": "rgb(102, 126, 234)", "bg": "rgba(102, 126, 234, 0.1)"},
            {"border": "rgb(240, 147, 251)", "bg": "rgba(240, 147, 251, 0.1)"},
            {"border": "rgb(79, 172, 254)", "bg": "rgba(79, 172, 254, 0.1)"},
        ]

        for idx, strategy in enumerate(top_strategies):
            scores = strategy["scores"]
            dataset = {
                "label": strategy["plan_name"],
                "data": [
                    scores["effectiveness"],
                    scores["coverage"],
                    scores["efficiency"],
                    scores["reliability"],
                ],
                "borderColor": colors[idx]["border"],
                "backgroundColor": colors[idx]["bg"],
                "borderWidth": 2,
                "fill": True,
            }
            radar_datasets.append(dataset)

        radar_data = {
            "labels": labels,
            "datasets": radar_datasets,
        }

        # Build score comparison chart script
        plan_names = [s["plan_name"] for s in ranked_strategies]
        effectiveness_scores = [s["scores"]["effectiveness"] for s in ranked_strategies]
        coverage_scores = [s["scores"]["coverage"] for s in ranked_strategies]
        efficiency_scores = [s["scores"]["efficiency"] for s in ranked_strategies]
        reliability_scores = [s["scores"]["reliability"] for s in ranked_strategies]

        comparison_data = {
            "labels": plan_names,
            "datasets": [
                {
                    "label": "有效性",
                    "data": effectiveness_scores,
                    "backgroundColor": "rgba(102, 126, 234, 0.8)",
                },
                {
                    "label": "覆盖率",
                    "data": coverage_scores,
                    "backgroundColor": "rgba(240, 147, 251, 0.8)",
                },
                {
                    "label": "效率",
                    "data": efficiency_scores,
                    "backgroundColor": "rgba(79, 172, 254, 0.8)",
                },
                {
                    "label": "可靠性",
                    "data": reliability_scores,
                    "backgroundColor": "rgba(67, 233, 123, 0.8)",
                },
            ],
        }

        script = f"""
        // Radar Chart
        const radarCtx = document.getElementById('radarChart').getContext('2d');
        const radarChart = new Chart(radarCtx, {{
            type: 'radar',
            data: {json.dumps(radar_data)},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {{
                    legend: {{
                        position: 'bottom'
                    }}
                }},
                scales: {{
                    r: {{
                        beginAtZero: true,
                        max: 100
                    }}
                }}
            }}
        }});

        // Score Comparison Chart
        const comparisonCtx = document.getElementById('scoreComparisonChart').getContext('2d');
        const comparisonChart = new Chart(comparisonCtx, {{
            type: 'bar',
            data: {json.dumps(comparison_data)},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                indexAxis: 'y',
                plugins: {{
                    legend: {{
                        position: 'bottom'
                    }}
                }},
                scales: {{
                    x: {{
                        beginAtZero: true,
                        max: 100
                    }}
                }}
            }}
        }});
        """

        return script

    def _get_recommendation_class(self, recommendation: str) -> str:
        """Get CSS class for recommendation badge"""
        mapping = {
            "强烈推荐": "strong",
            "推荐": "normal",
            "可选": "optional",
            "不推荐": "not",
        }
        return mapping.get(recommendation, "normal")

    def _get_score_class(self, score: float) -> str:
        """Get CSS class for score display"""
        if score >= 75:
            return "score-high"
        elif score >= 60:
            return "score-medium"
        else:
            return "score-low"

    def _build_minimal_report(self, ranking_results: Dict[str, Any]) -> str:
        """Build minimal report if template not available"""
        ranked_strategies = ranking_results.get("ranked_strategies", [])
        metadata = ranking_results.get("ranking_metadata", {})

        html = f"""
        <html>
        <head>
            <meta charset="UTF-8">
            <title>控制策略排序报告</title>
        </head>
        <body>
            <h1>控制策略排序评估报告</h1>
            <p>生成时间: {datetime.now()}</p>
            <p>基准方案: {metadata.get('baseline_plan_name', 'N/A')}</p>
            <p>输出组合: {metadata.get('output_combination', 'summary')}</p>

            <h2>策略排名</h2>
            <table border="1">
                <tr>
                    <th>排名</th>
                    <th>策略名称</th>
                    <th>总体评分</th>
                    <th>推荐</th>
                </tr>
        """

        for strategy in ranked_strategies:
            html += f"""
                <tr>
                    <td>{strategy['rank']}</td>
                    <td>{strategy['plan_name']}</td>
                    <td>{strategy['overall_score']:.1f}</td>
                    <td>{strategy['recommendation']}</td>
                </tr>
            """

        html += """
            </table>
        </body>
        </html>
        """

        return html


# Convenience function
def generate_ranking_report(
    ranking_results: Dict[str, Any],
    output_dir: str = None
) -> str:
    """
    Generate ranking report

    Args:
        ranking_results: Results from ranking engine
        output_dir: Output directory

    Returns:
        Path to generated report
    """
    generator = RankingReportGenerator()
    return generator.generate_report(ranking_results, Path(output_dir) if output_dir else None)
