#!/usr/bin/env python
"""
Script to regenerate DHS .add.xml files from control_strategy_config.json

This script:
1. Finds all DHS scenarios with control_strategy_config.json
2. Regenerates the .add.xml files using the corrected generate_dhs_xml function
3. Validates the generated XML has proper closingLaneReroute elements with time intervals
"""

import json
import logging
from pathlib import Path
from shared.control_tools.additional_generator import generate_strategy_xml

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def regenerate_dhs_xml_files():
    """Find and regenerate all DHS .add.xml files"""

    # Find all control_strategy_config.json files for DHS scenarios
    scenarios_dir = Path("output/scenarios/07_flowsurge")

    dhs_scenarios = []
    for config_file in scenarios_dir.glob("**/control_strategy_config.json"):
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                config = json.load(f)

            if config.get("strategy_type") == "DHS":
                dhs_scenarios.append({
                    "config_file": config_file,
                    "scenario_dir": config_file.parent,
                    "config": config
                })
        except Exception as e:
            logger.warning(f"Failed to read {config_file}: {e}")

    logger.info(f"Found {len(dhs_scenarios)} DHS scenarios to regenerate")

    # Regenerate XML for each DHS scenario
    for scenario in dhs_scenarios:
        scenario_dir = scenario["scenario_dir"]
        config = scenario["config"]
        strategy_type = config.get("strategy_type")
        parameters = config.get("parameters", {})

        # Extract event name from directory name
        # Format: scenario_{event_id}_{strategy_type}
        dir_name = scenario_dir.name
        parts = dir_name.split("_")
        if len(parts) >= 2:
            event_id = parts[1]  # e.g., "6120705" from "scenario_6120705_dhs"
        else:
            event_id = "unknown"

        # Determine the output XML filename
        add_xml_filename = f"scenario_flowsurge_{strategy_type.lower()}_{event_id}.add.xml"
        add_xml_path = scenario_dir / add_xml_filename

        logger.info(f"\n{'='*80}")
        logger.info(f"Processing DHS scenario: {dir_name}")
        logger.info(f"Output file: {add_xml_path}")

        try:
            # Generate XML using the corrected function
            xml_str = generate_strategy_xml(
                template_id=f"{strategy_type.lower()}_{event_id}",
                template={
                    "strategy_type": strategy_type,
                    "parameters_schema": []
                },
                parameters=parameters,
                strategy_type=strategy_type
            )

            # Validate XML content
            if "<closingLaneReroute" not in xml_str:
                logger.warning(f"  ⚠ Generated XML has no closingLaneReroute elements!")
                logger.warning(f"  Parameters: affected_lanes={parameters.get('affected_lanes')}")
                logger.warning(f"  Activation schedule: {parameters.get('activation_schedule')}")

            if "<interval" in xml_str:
                logger.info(f"  ✓ Generated XML contains interval elements")
                # Count intervals
                interval_count = xml_str.count("<interval")
                logger.info(f"  ✓ Number of intervals: {interval_count}")

            # Write to file
            with open(add_xml_path, 'w', encoding='utf-8') as f:
                # Add XML declaration and additional wrapper
                xml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- Generated by Event Scenario Generator -->

    <!-- Control Strategy -->
    {xml_str}

</additional>
"""
                f.write(xml_content)

            logger.info(f"  ✓ Successfully wrote {add_xml_path}")

            # Read back and validate
            with open(add_xml_path, 'r', encoding='utf-8') as f:
                generated = f.read()

            # Check content
            if "<closingLaneReroute" in generated:
                closing_count = generated.count("<closingLaneReroute")
                logger.info(f"  ✓ Verified: {closing_count} closingLaneReroute elements in file")
            else:
                logger.warning(f"  ⚠ WARNING: File has no closingLaneReroute elements after writing")

        except Exception as e:
            logger.error(f"  ✗ Error regenerating {scenario_dir.name}: {e}", exc_info=True)

    logger.info(f"\n{'='*80}")
    logger.info("Regeneration complete!")

if __name__ == "__main__":
    regenerate_dhs_xml_files()
