#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Regenerate All .add.xml Files for VSS/TEC Scenarios

This script regenerates all SUMO additional (.add.xml) files for VSS and TEC scenarios
after fixing the field name issues in additional_generator.py.

The script:
1. Scans all scenario directories for control_strategy_config.json files
2. For each VSS/TEC scenario, regenerates the .add.xml file
3. Preserves all other files (event XML, traffic config, etc.)

Author: Claude
Date: 2025-11-14
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any, List
import sys

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from shared.control_tools.additional_generator import generate_strategy_xml

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def find_all_vss_tec_scenarios(base_dir: Path) -> List[tuple[Path, str]]:
    """
    Find all VSS/TEC scenario directories with control_strategy_config.json.

    Returns:
        List of (scenario_dir, strategy_type) tuples
    """
    scenarios = []

    # Search in output/scenarios directory
    scenarios_dir = base_dir / "output" / "scenarios"
    if not scenarios_dir.exists():
        logger.warning(f"Scenarios directory not found: {scenarios_dir}")
        return scenarios

    # Find all control_strategy_config.json files
    for config_path in scenarios_dir.rglob("control_strategy_config.json"):
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)

            strategy_type = config.get('strategy_type', '').upper()
            if strategy_type in ['VSS', 'TEC']:
                scenario_dir = config_path.parent
                scenarios.append((scenario_dir, strategy_type))

        except Exception as e:
            logger.warning(f"Failed to read {config_path}: {e}")

    return sorted(scenarios)


def regenerate_add_xml(scenario_dir: Path, strategy_type: str, dry_run: bool = False) -> tuple[bool, str]:
    """
    Regenerate .add.xml file for a scenario.

    Args:
        scenario_dir: Path to scenario directory
        strategy_type: VSS or TEC
        dry_run: If True, don't save files

    Returns:
        (success: bool, message: str)
    """
    try:
        # Read control_strategy_config.json
        config_path = scenario_dir / "control_strategy_config.json"
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)

        parameters = config.get('parameters', {})
        strategy_name = config.get('strategy_name', strategy_type)

        # Generate strategy ID from directory name
        # Example: scenario_10754_vss -> vss_10754
        scenario_name = scenario_dir.name
        if '_' in scenario_name:
            parts = scenario_name.split('_')
            # Try to find event ID (numeric part)
            event_id = None
            for part in parts:
                if part.isdigit():
                    event_id = part
                    break

            if event_id:
                strategy_id = f"{strategy_type.lower()}_{event_id}"
            else:
                strategy_id = f"{strategy_type.lower()}_{scenario_name}"
        else:
            strategy_id = f"{strategy_type.lower()}_{scenario_name}"

        # Create a minimal template dict (additional_generator doesn't use it much)
        template = {
            "strategy_type": strategy_type,
            "strategy_name": strategy_name
        }

        # Generate XML
        xml_content = generate_strategy_xml(
            template_id=strategy_id,
            template=template,
            parameters=parameters,
            strategy_type=strategy_type
        )

        # Wrap in <additional> root element
        full_xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- Generated by Event Scenario Generator -->

    <!-- Control Strategy -->
    {xml_content}

</additional>
'''

        # Find .add.xml file
        add_xml_files = list(scenario_dir.glob("*.add.xml"))

        if not add_xml_files:
            # Create new filename
            event_type = scenario_dir.parent.name
            if event_type.startswith(('01_', '02_', '03_', '04_', '05_', '06_', '07_')):
                event_type_name = event_type.split('_', 1)[1] if '_' in event_type else event_type
            else:
                event_type_name = event_type

            add_xml_path = scenario_dir / f"scenario_{event_type_name}_{strategy_type.lower()}_{event_id if event_id else 'unknown'}.add.xml"
        else:
            # Use existing filename
            add_xml_path = add_xml_files[0]

        # Save XML
        if not dry_run:
            add_xml_path.write_text(full_xml, encoding='utf-8')

        return True, f"Regenerated {add_xml_path.name}"

    except Exception as e:
        return False, f"Error: {e}"


def main():
    """Main execution function."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Regenerate all .add.xml files for VSS/TEC scenarios'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without modifying files'
    )
    parser.add_argument(
        '--base-dir',
        type=Path,
        default=Path(__file__).parent.parent,
        help='Base directory of the project (default: parent of scripts/)'
    )
    parser.add_argument(
        '--sample',
        type=int,
        metavar='N',
        help='Only process first N scenarios (for testing)'
    )

    args = parser.parse_args()

    logger.info("=" * 80)
    logger.info("Regenerate VSS/TEC .add.xml Files")
    logger.info("=" * 80)

    if args.dry_run:
        logger.info("DRY RUN MODE - No files will be modified")

    # Find all VSS/TEC scenarios
    logger.info(f"\nSearching for VSS/TEC scenarios in {args.base_dir}")
    scenarios = find_all_vss_tec_scenarios(args.base_dir)
    logger.info(f"Found {len(scenarios)} VSS/TEC scenarios")

    if args.sample:
        scenarios = scenarios[:args.sample]
        logger.info(f"Processing first {args.sample} scenarios (sample mode)")

    # Count by type
    vss_count = sum(1 for _, st in scenarios if st == 'VSS')
    tec_count = sum(1 for _, st in scenarios if st == 'TEC')
    logger.info(f"  VSS: {vss_count}, TEC: {tec_count}")

    # Regenerate each scenario
    vss_success = 0
    tec_success = 0
    vss_failed = 0
    tec_failed = 0

    for scenario_dir, strategy_type in scenarios:
        scenario_name = scenario_dir.name

        success, message = regenerate_add_xml(scenario_dir, strategy_type, dry_run=args.dry_run)

        if success:
            status = "Would regenerate" if args.dry_run else "Regenerated"
            logger.info(f"  ✓ {scenario_name} ({strategy_type}): {status} - {message}")
            if strategy_type == 'VSS':
                vss_success += 1
            else:
                tec_success += 1
        else:
            logger.error(f"  ✗ {scenario_name} ({strategy_type}): Failed - {message}")
            if strategy_type == 'VSS':
                vss_failed += 1
            else:
                tec_failed += 1

    # Summary
    logger.info("\n" + "=" * 80)
    logger.info("SUMMARY")
    logger.info("=" * 80)
    logger.info(f"Total scenarios processed: {len(scenarios)}")
    logger.info(f"\nVSS Scenarios:")
    logger.info(f"  Success: {vss_success}")
    logger.info(f"  Failed: {vss_failed}")
    logger.info(f"\nTEC Scenarios:")
    logger.info(f"  Success: {tec_success}")
    logger.info(f"  Failed: {tec_failed}")

    total_success = vss_success + tec_success
    total_failed = vss_failed + tec_failed

    if args.dry_run and total_success > 0:
        logger.info("\n⚠️  This was a dry run. Re-run without --dry-run to apply changes.")
    elif total_failed > 0:
        logger.warning(f"\n⚠️  {total_failed} scenarios failed to regenerate. Check errors above.")
    else:
        logger.info("\n✅ All .add.xml files regenerated successfully!")
        logger.info("Next step: Run verify_vss_tec_xml.py to verify the fixes")

    logger.info("=" * 80)

    return 0 if total_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
